---
vms:
  server:
    count: 2
    role: server
    os: rhel9
    additionalDisks:
      - name: data
        storage: 90Gi
      - name: extra
        storage: 40Gi

  desktop22:
    count: 1
    role: desktop22
    os: windows2k22
    dataSource: windows2k22
    efi: true
    storage: 90Gi
    additionalDisks:
      - name: data
        storage: 80Gi
    ports:
      - name: ssh
        port: 22
        protocol: TCP
        targetPort: 22
      - name: rdp
        port: 389
        protocol: TCP
        targetPort: 389

  desktop25:
    count: 1
    role: desktop25
    os: windows2k25
    dataSource: windows2k25
    efi: true
    storage: 50Gi
    additionalDisks:
      - name: data
        storage: 80Gi
    ports:
      - name: ssh
        port: 22
        protocol: TCP
        targetPort: 22
      - name: rdp
        port: 389
        protocol: TCP
        targetPort: 389

vmNamespace: gitops-vms

registryCredentialExternalSecrets:
  quay-creds:
    vaultKey: secret/data/hub/quay-image-robot

externalDataSources:
  - name: windows2k22
    type: registry
    url: "docker://quay.io/martjack/windows-server-2022-standard:latest"
    size: 90Gi
    registryCredentialsSecret: quay-creds

  - name: windows2k25
    type: registry
    url: "docker://quay.io/martjack/windows-server-2025-standard:latest"
    size: 90Gi
    registryCredentialsSecret: quay-creds

serviceAccountName: gitops-vms-sa

rbac:
  roleBindings:
    - name: view-machine-api
      createBinding: true
      scope:
        cluster: false
        namespace: "openshift-machine-api"
      subjects:
        kind: ServiceAccount
        name: gitops-vms-sa
        namespace: gitops-vms
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: view-machine-api
