---
vms:
  server:
    count: 2
    role: server
    os: rhel9
    additionalDisks:
      - name: data
        storage: 80Gi
      - name: extra
        storage: 40Gi

  desktop:
    count: 1
    role: desktop
    os: windows2k22
    dataSource: windows2k22
    efi: true
    mainDiskStorageBus: sata
    storage: 50Gi
    additionalDisks:
      - name: data
        storage: 80Gi
    ports:
      - name: ssh
        port: 22
        protocol: TCP
        targetPort: 22
      - name: rdp
        port: 389
        protocol: TCP
        targetPort: 389
vmNamespace: gitops-vms

registryCredentialExternalSecrets:
  quay-creds:
    vaultKey: secret/data/hub/quay-image-robot

externalDataSources:
  - name: windows2k22
    type: registry
    url: "docker://quay.io/martjack/windows_image:latest"
    size: 50G
    registryCredentialsSecret: quay-creds

serviceAccountName: gitops-vms-sa

rbac:
  roleBindings:
    - name: view-machine-api
      createBinding: true
      scope:
        cluster: false
        namespace: "openshift-machine-api"
      subjects:
        kind: ServiceAccount
        name: gitops-vms-sa
        namespace: gitops-vms
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: view-machine-api

waitForMetalNode: false
