---
clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    vault:
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    openshift-cnv:
    openshift-storage:
    gitops-vms:
    openshift-workload-availability:
      operatorGroup: true
      targetNamespaces:
    openshift-mtv:

  subscriptions:
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1

    openshift-virtualization:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      channel: stable

    node-health-check:
      name: node-healthcheck-operator
      namespace: openshift-workload-availability
      channel: stable

    self-node-remediation:
      name: self-node-remediation
      namespace: openshift-workload-availability
      channel: stable

    openshift-data-foundation:
      name: odf-operator
      namespace: openshift-storage

    migration-toolkit-for-virtualization:
      name: mtv-operator
      namespace: openshift-mtv
      channel: release-v2.11

  argoProjects:
    - hub

  imperative:
    jobs:
      - name: deploy-kubevirt-workers
        playbook: ansible/deploy_kubevirt_workers.yml
        verbosity: -vvv
      - name: clean-golden-images
        playbook: ansible/odf_fix_dataimportcrons.yml
        verbosity: -vvv
    clusterRoleYaml:
      - apiGroups:
          - "*"
        resources:
          - machinesets
          - persistentvolumeclaims
          - datavolumes
          - dataimportcrons
          - datasources
        verbs:
          - "*"
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - get
          - list
          - watch

  applications:
    ensure-openshift-console-plugins:
      name: ensure-openshift-console-plugins
      namespace: openshift-console
      argoProject: hub
      chart: ensure-openshift-console-plugins
      chartVersion: 0.1.*
      extraValueFiles:
        - '$patternref/overrides/values-console-plugins.yaml'

    vault:
      name: vault
      namespace: vault
      argoProject: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*

    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      argoProject: hub
      chart: openshift-external-secrets
      chartVersion: 0.0.*

    openshift-cnv:
      name: openshift-cnv
      namespace: openshift-cnv
      argoProject: hub
      chart: openshift-virtualization-instance
      chartVersion: 0.1.*

    odf:
      name: odf
      namespace: openshift-storage
      argoProject: hub
      chart: openshift-data-foundations
      chartVersion: 0.2.*
      extraValueFiles:
        - '$patternref/overrides/values-odf-chart.yaml'

    gitops-vms:
      name: gitops-vms
      namespace: gitops-vms
      argoProject: hub
      chart: edge-gitops-vms
      chartVersion: 0.5.*
      extraValueFiles:
        - '$patternref/overrides/values-vsk-vms.yaml'

    node-health-check-operator:
      name: node-health-check-operator
      namespace: openshift-workload-availability
      argoProject: hub
      chart: node-health-check-operator
      chartVersion: 0.1.*

  # Only the hub cluster here - managed entities are edge nodes
  managedClusterGroups: []
